😄 fix texcompile 😄

diff --git a/.local/bin/tools/texcompile b/.local/bin/tools/texcompile
--- a/.local/bin/tools/texcompile
+++ b/.local/bin/tools/texcompile
@@ -9,7 +9,7 @@ printf "This script will compile LaTeX every time you save a file in neovim.\nAn
 exit 0
 }
 
-faillastcompiled(){
+faillastcompiled(){ # Function which will show error message saying "no file compiled."
 printf "No file compiled.\n" && notify-send "No file compiled." && exit 1
 }
 
@@ -20,14 +20,23 @@ zathura "$lastcompiled" >/dev/null 2>&1 &
 exit 0
 }
 
+error(){ # Error function
+printf "ERROR!\n"
+exit 1
+}
+
+# Arguments
 case "$1" in
 	-l|--last) openlastcompiled ;;
 	-h|--help) help ;;
 esac
 
+# Check if file was inputed.
 [ -z "$1" ] && printf "No file inputed.\n" && exit 1
 
-pdflatex "$1" || exit 1
+# Compile document
+pdflatex "$1" || error
 
+# Remove extension and put that in /tmp/lastcompiled
 noextension=$(echo $1 | awk -F"." '{print $1}')
 echo "$(pwd)/$noextension.pdf" > /tmp/lastcompiled
